THE ENTREE
On the seventeenth of June I received an invitation for a formal buffet dinner at the mayor’s private summer estate that very same evening. I spent hours getting my hair right, then put on my best dress and prettiest shoes - with matching purse - and got picked up by a fancy black car and a driver that didn’t say a word. I was used to this; my parents’ driver never said a word either while he drove me around town. I was rather excited; it wasn’t common to dine with the mayor, even for people in my status, let alone in his private residence. 
The driver took me to a place I had seen on TV, though never up close. The car slowly made its way through a set of heavy iron gates with brass detailing that opened automatically when he drove up to them and closed behind him right away. He drove all the way up to the steps leading to a big, oak double door where the turning circle allowed the car to pull up sideways. At that exact moment the large doors opened up and another man came through them, opened the car door for me and helped me out and taking my purse.
‘Welcome!’ the man happily exclaimed. ‘My name is Howard Jackson; I’ll be your host this evening. If there’s anything you need, don’t hesitate to ask. Allow me to escort you to the dining room.’ He turned around and climbed the steps to the front door. Struggling not to trip on my dress I tried to keep up with him as he passed the front door into the entrance hall.
The entrance hall was huge. There was a dark, red carpet going from the front door to a majestic set of white-marble steps leading to the second floor. Where the carpet wasn’t red it had a  charming,  emerald-green color and lead to the numerous corridors and doors, all guarded by sets of genuine looking Reconquista armor sets. The ceiling, two floors higher, was a true masterpiece. It had a large dome with arched windows flanked by white-marble, innocent angels in between. The wealth and beauty was nearly overwhelming.
Howard followed one of the green lanes in the carpet into a corridor on the left of the staircase. I looked at the paintings and tapestries on the walls between the doors while trying to ignore the sound of my high heels on the wooden floorboards. Every door had a shiny, aluminium plaque next to it with bright blue letters indicating the room’s number and contents, contrasting the medieval theme. I started to regret wearing high heels, I had always preferred flats and my feet were starting to hurt. Perhaps I could subtly take them off during dinner and keep them under the table. 
Moments later we entered the dining room. Suits of armor stood alongside every door, massive tapestries were mounted on every wall and massive brass chandeliers hung high above the biggest dinner table I had ever seen. Fourteen massive, throne-like chairs were neatly set at the table with a porcelain plate, silver cutlery and a marble nameplate placed in front of them. The food was already stacked on the table, plentiful and still steaming, making me realize how hungry I really was. There were a few people already there, digging into the food. A bell rang in the distance and Howard excused himself, saying another guest had arrived and that he would store my purse on a secure place.
I walked past the chairs looking for my seat. Eventually I found my nameplate between Jaylynn Matthews, who was hunched over her plate chewing on a chicken leg, and Simon Rhodes, who hadn’t arrived yet.
‘Hey,’ I said as I sat down, speechless at how comfortable a chair could be.
‘You should try the chicken, it’s amazing,’ Jaylynn replied, half looking at me over her plate. She spoke with a flawless British accent, catching me off guard.
‘I’ll take your word for it,’ I said. I took my shoes off with a relieved sigh and poured myself a cup of coffee.
An hour later the only seat still empty was that of the mayor himself, seated on one of the ends next to a girl called Nicky Ivers. Most people were done eating by then, save Jaylynn, and were sitting back in their chairs. They sipped their drinks and most were realizing they had probably eaten too much as they chatted with the other people on the table. Most of us had never seen any of the others and were still in the process of getting to know one another. Jaylynn and I seemed somewhat accustomed to each other. We seemed to have created some sort of bond in our mutual appreciation of silence. 
Upon his arrival Simon had shaken my hand and introduced himself courtly, but had given me no further attention. He was leaned over to his other side and in a conversation with David Evans who was seated there. I listened in on their conversation from time to time only to realize they were solely discussing cars and girls. I would roll my eyes, sip my coffee and try to focus my attention elsewhere.
The nameplates were labeled on both sides, which meant I could tell everybody’s name even without knowing them. I had discovered Jaylynn had a little sister called Sarah, who was sitting on the end of the table on our left. Other than physically being an almost exact copy of each other, they didn’t seem to have much in common. Sarah was happily chatting and giggling with the girl next to her called Thalia Dawson. The two seemed as if they had been friends for years and were completely unbothered by the fact that the guy on Sarah’s other side, Tristan Black, was being obnoxiously loud in his conversation with Gary Donnaghue next to him. Their conversation was very similar to that of David and Simon. Across from me, next to Gary, sat Sue Williams. Presumably David’s little sister. She felt very out of place and was quiet throughout the entire dinner, shooting helpless looks in David’s direction, but he never looked back at her.
On Sue’s other side were Eirin Clark and Reuben Hayes who made their relationship more apparent than anyone wanted it to be. Their plates were still sparkling clean because the two lovebirds hadn’t let go of each other for one second. They seemed only to separate their lips to gasp for air.
Howard came back in, followed by a group of masked men in ninja-like uniforms. They scattered throughout the dining room, locking all doors and then standing guard next to them.
‘They’re carrying Kalashnikovs,’ Jaylynn noticed. AK47’s; I’d seen them too. She finally stopped eating and moved her chair back to get up.
‘What are you doing?’ I asked.
‘I have to get to my sister,’ she explained, but as soon as she got up two of the guards hurried her way.
‘Please remain seated, miss Matthews,’ Howard said. He seemed stressed, and none of the chivalry he had shown upon our arrival remained. A restlessness had dawned over the people at the table and even Reuben and Eirin had separated their faces.
‘The mayor couldn’t make it,’ Howard clarified as he leaned his hands on the mayor’s chair. Given the sudden presence of automatic rifles no one was too worried about whether the mayor was present. We weren’t sure if the rifles were friendly but the general atmosphere in the room didn’t seem to be. 
‘It matters very little,’ Howard added. I noticed he had a handgun holstered at his belt.
‘For your own safety we’ve decided to keep you here until further notice,’ he said.
‘What do you mean for our own safety?’ Gary asked. ‘Has something happened outside?’
‘Not at all, we just don’t want you to leave.’
‘So you’re kidnapping us,’ Tristan said.
‘Not at all, you all came here voluntarily, did you not? It’s more of a hostage situation.’ The guards seemed to grow restless too, which is a bad thing with armed people.
‘So how is it for our safety?’ Simon asked.
‘Because if you don’t, we shoot you.’ One of the guards raised his gun and they all sniggered while the people at the table went quiet. Sue got very pale while Sarah and Thalia seemed closer to tears than the giggling they had shared earlier.
‘Very well,’ Howard continued while drawing a folded sheet of paper from his inside pocket. ‘We’ve taken the liberty to ready a set of rooms for you. You have been paired per two or three and strongly recommend not trying to trade places given aforementioned reasons.’ He gestured at the armed guards and unfolded the paper.
‘Right, our safety,’ Jaylynn whispered under her breath. In any other situation it would have made me smile. The armed guards walked up to us and flanked each of us. Then everything went very quickly. The men grabbed us by our upper arms, one on each side, and dragged us out of our chairs.
‘Here’s the plan,’ Howard yelled above our panicked cries. ‘You people are going to do exactly what we say, when we say it.’ Next to me Jaylynn was struggling and kicking the men holding her so much that two more men came to hold her down. Tristan also fought back bravely, one of the guards stumbled back crying in pain while two others took his place. ‘You’re going to keep quiet,’  Howard continued. ‘Regardless of what you hear, or feel, or think, because if you do not, we will make sure you will never make another sound ever again.’ The guards started to drag us out of the dining room while Howard recited the groups. I couldn’t hear a word he said, but apparently Jaylynn had.
‘Take care of her, Ash!’ she cried, still struggling. We were lead into a corridor that was not decorated like the others. The doors here were made of steel and the walls were a mere grey. I cried for help like the others and tried to struggle. One of the guards put his gloved hand on my mouth and held it shut. His hand was big and strong, pushed slightly against my nose stopping my breathing completely. The sudden silence gave away that others had gotten a similar treatment. I choked, my eyes filled with tears making my sight go blurry and I couldn’t keep up with the guards. I tripped over my bare feet and my dress tore as the guards stepped on it, ruthlessly dragging me along. I tried to gasp for air but got no mercy and slowly my sight went from blurry to darker until I passed out completely.

I woke up with a major headache. I rubbed my eyes, trying to make the headache go away. I slowly started to realize there was more aching than just my head and tried to remember what had happened. While the memories from the dinner party started to flood my head, making the headache all the worse, I shot up straight and opened my eyes. I ignored the dizziness and rested my back against the wall as I took a look around the room.
My vision was still slightly blurry, but there wasn’t a lot in the room either way. There was a steel door on the other side of the room and nothing else. On this side were two small beds on either side of a small window. The window had an iron cross welded into the frame; even if we managed to break the glass it would be too small to climb through. The beds had a grey, metal frame that blended in with the grey walls. There was a filthy mattress on them that was nowhere near as comfortable as the bed I slept on at home. Jaylynn’s little sister, Sarah, was on the other bed and seemed to still be passed out lying flat on her stomach with her arms and legs spread slightly and her mouth ajar. She was wearing a red tracksuit with black facings, severely contrasting the colorless atmosphere of the room but more disturbingly it wasn’t the pretty dark-blue dress I had seen her wear during the dinner. I looked down at myself and saw the same red and black tracksuit on me too.
A slight nausea rose in my stomach. I didn’t appreciate being touched, let alone by strangers, especially while unconscious. I zipped the jacket open to discover a black t-shirt. It felt cheap, and uncomfortable. I pulled it up slightly, with growing anxiety, and pulled on the elastic waist-band of the pants to look inside. The nausea intensified as I saw the black panties I was in. I hadn’t been in these when I came here. Those had been red, slightly sensual, and suited the dress I was wearing at the time. Someone had changed my clothes, including my underwear, so they had seen me naked, while I was unconscious. I was here involuntarily, who knows what else they had done?
My breathing quickened and I backed into the corner of my bed. I wrapped my arms around my legs and rested my forehead at my knees, trying to comprehend the situation I had ended up in. I realized I had no proof in any way that the mayor was actually involved. According to Howard he never showed up, I was starting to think he was never invited. This could all have been some elaborate set-up to get us all at one place, but to what use?
I knew of most of the people I had seen at the table. Though I hadn’t met many of them in person before, I knew they were all children of the wealthiest people in the area. Usually the kids of the rich get kidnapped over a ransom but even though I hadn’t fallen victim to that myself, this didn’t seem like the stories I’d heard. As far as I knew, they would get snatched off the streets, or at school, and kept in a van or basement until either the money came in or they got out, one way or the other. On rare occasions they would be abused, beaten black and blue or even raped, but they would still be in their own clothes or what was left of them. They were not fed high quality chicken and were not put in bright colored track suits while passed. Thirteen teens kidnapped at the same time by the same people was highly unusual, to say the least, and more than a little suspicious.
On the bright side, being part of the rich and famous had its perks in times like these. It meant that in no time the whole country would be looking for us, as soon as people realized we were missing. Some of the parents had a small army or private investigators keeping an eye on the family members. The magnitude of the kidnapping would mean the feds would be on it in no time, too. I’d seen enough police shows to know what was going to happen. They would check the private security footage and track the license plates and in less than a day the place would be swarming with cops and news vans to tell the world we were safe. We just had to hold out up to that point, and that couldn’t be far away. I felt a little better realizing that.
Sarah groaned and rolled over, then slowly pulled herself up straight and sat up against the wall.
‘I’m in pain,’ she said in the same British accent her sister had intrigued me with. She didn’t seem too troubled with the situation we were in, perhaps she’d already drawn the same conclusions I had come to. I looked at her without answering. She looked back at me, rubbing her temples.
‘Ashley, right?’ she asked after dropping her arms. She looked around the room.
‘Yeah,’ I answered. The talking hurt my head but somehow the silence seemed to hurt more. ‘And you’re Sarah,’ I added. ‘I sat next to your sister at dinner.’
‘She seemed to get along with you. And that’s a compliment, she doesn’t exactly get along with everyone.’ She got up and examined the iron cross that barred the window.
‘Why’s that?’ I asked. She looked at me before answering.
‘Let’s just say this isn’t our first abduction,’ she answered coldly, carefully avoiding eye contact. She walked over to a half-wall  on the other side of the room. I hadn’t noticed it earlier; it was the same color as everything around it.
‘Oh, that’s lovely private,’ she said more to herself than to me. She came back and crashed onto the bed. ‘Looks like we’re stuck in here, for now,’ she added.
‘Bummer, I planned on walking out the front door,’ I replied sarcastically. She half grinned; we would get along alright. It had quickly gotten dark outside, rather suddenly, and with that inside too. There seemed to be no electricity in room and no lighting either. The darkness seemed to bring some fear up in Sarah.
‘Ashley?’ she asked. We had been quiet for a while and her voice was much softer now. Much more fragile.
‘What’s up?’ I replied. She waited a while more before she replied.
‘Can I trust you?’ It seemed to matter  lot to her, but frankly I didn’t know what to say.
‘I’d like to think so,’ I said. ‘Something bugging you?’
‘I’m scared of the dark.’ She said it fast and barely louder than a whisper. I wasn’t sure how to respond.
‘What are you afraid of in the dark?’ I asked her. My eyes had adjusted to the lack of light, I could see Sarah on her bed, curled up against the wall. She had her eyes closed.
‘I don’t know, I’m just scared of it,’ she reasoned, tearing up. I couldn’t cope well with crying people, less so when alone with them with no escape.
‘I’m here with you, I’ll keep you safe,’ I said. Cliché as it was, it seemed like the right thing to say. ‘Do you want me to hold you?’ I added. She opened her eyes and looked at me, unsure.
‘I think so,’ she admitted. I crawled closer to the wall on my bed.
‘Come over then, I’ll hold you through the night.’ She shook her head.
‘I can’t come over, there might be something under the bed and it will grab me if I step on the floor,’ she whispered. The tears rolled down her face and she wiped them off with her sleeve.
‘I’ll come to you, if you want,’ I said. She nodded. I got up and, without touching the floor, jumped to her bed where I laid down and put my arm around her.
‘Why did you jump?’ she asked, crawling deeper into my hold.
‘I couldn’t risk touching the floor, could I?’ She smiled weakly and dozed off. I Realized there was nothing else we could do and I fell asleep not much later.

