[Part Four]
    
At that moment numerous neutral angels had gathered on the Scandinavian peninsula. They met on a small island in the Kalix river, just north of the Swedish town Vallen, not far from the border with Finland. It was a small, uninhabited island with mostly trees, which the couple dozen angels that had showed up used as cover. The neutral angels were those that refused to side with either Dominick or Lydia and they had become a third party during the deviation. A minority, and mostly left alone in a mutual sense of respect. Only neutral angels that provoked an outrage ended up in the crosshairs of either dark or light angels. They commonly lived far from the light and dark tribes, to make sure they were not mistaken for enemy angels and to ensure their peace and quiet. Only the angelic warfare had escalated beyond the ordinary and more neutrals had fallen victim to matters they had no business in, which is exactly why this meeting had been called.
‘Friends,’ said a deep voice. Tarben Gautam had spoken without raising his voice but the crowd had quieted down at once. He exuded a sense of security that accredited him unspoken authority.
‘The fight that Dominick brought upon us has diverted many from their divine obligations,’ Tarben continued. He was big and muscular, his hair and his beard were long and black with some grey locks peeking through. His ancestry was evidently local, and Viking and the expression on his face spoke volumes; he was displeased, but kind. Several attendees had nodded in agreement as he spoke.
‘Those of us that have successfully held themselves averted from the juvenile acts of dark and light can no longer stand idly by; the demeanors of those involved are costing the lives of innocents; unknowing and neutral alike. I have called you here to propose a Neutral Alliance, pledging solely to the divine and angelic duty that was bestowed upon us by the Cumulonimbus.’ Tarben looked around at the group that had gathered. They all seemed to agree with him. Of course they did, otherwise they would not have come here. Kalix wasn’t exactly around the corner for most of these people, and he had given them the opportunity to respond beforehand. He’d send a letter to all neutral angels he was aware of. In it, he had explained his plans for the Neutral Alliance. The responses he’d received were moreover positive. People agreed that the dark and light angels had taken their disagreement too far. Unofficially, The Alliance already existed; this meeting was more a formality for the history books.
‘We have tried to reason with Enypheo Nagy, leader of the light angels, and Seren Velazquez, leader of the dark angels. They would not listen to words.’ The crowd chanted some mean words meant towards the dark and light angels and Tarben smiled. He liked the attention.
‘Perhaps they will listen to deeds!’ he added, turning the crowds chants into praise. He laughed with them for a moment, then gestured for them to quiet down, which they did.
‘Construction of our headquarters has begun in Malmö,’ Tarben continued. ‘I will personally oversee the process and progress thereof which means until that’s completed I will stay in Sweden. It also means I have chosen other people to carry out the tasks I spoke of in my letter.’ The crowd listened intensely, hoping they would be picked.
‘I have chosen Mateo Rodriquez to retrieve the daughter of Abila, called Jacintha. She has been hidden in caverns below Barcelona and Mateo is familiar with the region.’ A Spanish looking guy had separated himself from the crowed and bowed as he took place next to Tarben. Mateo wasn’t young, but he seemed very vital. A teenage girl followed him to Tarben, taking place half behind Mateo. She had long, curling hair and brown eyes so mesmerizing they surprised Tarben. He needed a moment before continuing and was glad she’d taken place outside his line of sight.
‘He has decided to take his daughter Esther with him to face the dragon, after which she will attempt to infiltrate into the dark angel ranks and earn their trust.’ A devious smile appeared on Esther’s face that neither Mateo or Tarben noticed. A young woman made her way up to Tarben at that same moment and she did notice, but didn’t seem to care. She took place on Tarben’s other side while he explained her task.
‘As for our plans with Agate: It can be found sufficiently in Iceland. A team lead by Lavinia Tremayne will set up a base in Kálfafell after which they will try to convince the locals to aid our cause.’ The woman nodded in agreement. 
‘After that,’ he continued, ‘Lavinia will travel to England and infiltrate in the light angel ranks while her team remains in Iceland to create a monopoly in the trade for Agate.’ 
Mateo and Esther had left the island and were already on their way to Barcelona while Lavinia headed back into the crowd, to handpick only the best to join her to Iceland. Tarben looked at the crowd and smiled. They had made history today, and everything would turn out in their favor.



‘It’s important that you understand what you’re up against,’ explained Mistress Enypheo Nagy.  Theodore was in her office with her, and tried to remember everything. ‘As you are not an angel, you have no knowledge of which kinds of magic they can perform. Nor  about who of us are more dangerous than others and thus am I to enlighten you to ensure that you are able to survive.’
Theodore, petrified by nerves and eager not to miss or forget anything, sat in his chair and gave a slight nod.
‘There are five kinds of magic as there are five elements: fire, water, wind, earth, and aether. First; fire. We use fire to attack with, to light our way and sometimes even to warm us. When combining it with aether magic, we can create various balls which have different colors. We call those “suns.” Each color represents a different effect, as each kind of fire has a different effect. Not all kinds of fire are harmful, for example, the purple sun is a sign of life.’
Mistress Enypheo cast a purple ball of fire and let it float above the table.
‘This sun needs no oxygen and will not extinguish, unless I tell it to myself, or if I die, for I cast it. I could put effort in teaching you all the different colors and their meaning, but I’ll leave that up to your trainer as you have enough to take in at the moment. Any questions so far?’
‘Who will be my trainer?’ Theodore asked.
‘You’ll meet her in due time, at the moment it matters little. Try to focus, Ted.’
‘Yes madam.’
‘Good. As for the other kinds of magic, I’ll keep it short: We angels use 3 other kinds of magic: Water; with which we can create shields to absorb a limited part of the damage caused on us. Wind; with which we create flows of air to bend the course of incoming fire. And earth; with which we create obstacles to fully block fire or simply to annoy our foes. None of our elements work without the aether magic, however. Alike “the force” from that “Star Wars trilogy” mortals seem to enjoy, it has to be with you.’
“Trilogy, not saga,” Ted realized, cracking a smile. He was starting to like Enypheo more.
‘Exceptionally well trained angels, the so-called untouchables, are able to backfire attacks by sending stronger fire at the incoming fireballs, but untouchables are rare, there are only about a hundred untouchables in the world, of which eighty-five are dark angels. Understood?’
‘Understood.’ Theodore looked at the water and earth that Enypheo had created on the desk, he still felt the air.
‘Now, untouchables are so well-trained that most of them care little about breaking the rules and as the only way to kill an angel is to severely break the rules it does not often happen, luckily. But you will have to know what to expect. Untouchables can only get caught by other untouchables, that is why they usually get away with murder.’
She casted a black ball of fire, the so-called sun of death, she said. Theodore remembered more of his childhood he was so eager to forget. He saw his sisters eyes, the eyes of Luca McGuire, the way he had seen them last, in a head without a body looking at him in evermore agony. 
‘Only untouchables dare cast this sun, it is the only way to kill an angel,’ Enypheo said. ‘It comes at a price, if you successfully use one your lose your aether for two – Are you alright, Theodore?’
Theodore did not hear her, it was all too much. He fell to the ground as he lost consciousness.
<i>Somebody knocked on the door, hard.
‘Open up!’ a voice bellowed. Theodore climbed out of bed as thunder camouflaged a second wave of knocks. Rain was pouring down outside as it had done for the past few days. He used the light of his dad’s purple sun which was still shining under the glass to look for the key to the front door. His sister entered the room.
‘Who’s at the door?’ she asked.
‘Go back to bed, Luca,’ replied Theodore, but she did not obey.
The door burst open, whoever was outside dared not wait any longer. The lightning outside threw a long, dark shadow into the room and both Theodore and Luca fell back in shock. The man in the door-opening was wearing a long, black coat which seemed to grow right out of his also long and black hair. He looked evil in the children’s eyes.
‘Where’s that evil whore?’ the man said, rather to himself than to the children. He casted a black sun with his right hand as he stepped into the room and looked around. Luca gasped for she realised what Theodore had already seen, the man had casted the sun of death.
Even though Luca was no less than six years younger than her brother, she was all the more experienced with the magic their father taught them before he disappeared, Theodore had never quite gotten the hang of it. Luca casted a shield of water to protect herself. The man looked at it, then approached Theodore instead and played with the deadly ball of fire before his eyes.
‘Why don’t you tell me where your mother is, boy. Maybe I’ll let you live.’
‘She’s dead,’ said Luca. ‘Theodore, tell him she’s dead!’ Both the man and Theodore looked at her in equal surprise.
‘That is a lie,’ said the man. ‘Sally is not dead, much unlike you.’
The sun shot in her direction, shattered the shield that was supposed to protect her and flew straight into the girl.
Luca screamed in throes of agony as her eyes ignited in black flames and she was lifted into the air while more and more blood flowed out of her mouth and nose. Her white-blond hair turned red at the touch of her blood while she herself turned whiter and whiter still while the blood left her body, now no longer just through her mouth and nose but other places as well, as the fire from her own eyes seemed to cut through her arms and legs. She was now fully ignited in the black flames of the sun of death and she screamed ‘Help me!’ with what seemed to be her last bit of consciousness. She looked at Theodore in terror, and the shocked Theodore looked back in helplessness. He could not make a sound, scared as he was. The man laughed.
‘Never lie to Mallory Andrews! Never!’ he yelled laughing all the more as the girl now exploded. There were parts of her body everywhere and blood on all walls and her head rolled through the room and stopped right in front of Theodore, Luca’s eyes evermore looking in agony in his direction.
Luca McGuire was dead.
‘Now I will ask you this once more, Theodore,’ said Mallory slowly. ‘Where is your mother?’
From the corner of his eye he saw the purple sun that had been his hope for so long. It extinguished while he looked. The man picked up Luca’s head by her hair, quickly searched the house and then left.</i>





