EQUITY
/* Revenge/Romance story concept about a young girl seeking revenge for the ominous slaughter of her family. She was to land in a dark and deceiving world full of secrets, where she would meet a boy who would change everything. /*

Evelynn quietly pulled the window open, graciously slid through and closed it without making a sound. She threw one last look into the dark, empty street before she backed away into the shadows of the abandoned house. The door to the staircase was locked, but there was a small hole in the wall which Evelynn used to gain access to the staircase. She knew the place well, as she had claimed it as her own. The tracks in the dust went upstairs and she followed them, carefully avoiding the steps she had marked before. She reached the top of the staircase where she used a small cabinet to reach for the hole in the ceiling through which she pulled herself onto the attic. She shoved a wooden plate onto the gap as makeshift trapdoor, making it harder to spot from beneath and ensuring she wouldn’t fall out.
This attic seemed to have become her home. Sort of, anyway. An old, dirty mattress in the corner with a thin blanket filled with holes served as her bed. She’d roll up her sweatshirt if she wanted a pillow. At the end of the mattress was a half-open backpack that appeared to be empty. Next to it was a pile of clothes, none of which were clean. On the contrary, they smelled damp - as did everything - and it looked like some of the clothing, if not all, had been stained with blood. During the day she’d get most her light from a tiny , busted window in the roof, right above the trapdoor, but when it was dark out, like now, she’d light a candle on a table on the other end of the attic.
She washed her hands at a tap next to the table with a bucket beneath it, then drew a three inch butterfly knife from her pocket and threw it on the ground next to the mattress, where it landed next to a picture of a girl half Evelynn’s age. The frame was worn down and the glass broken. The girl in the photograph showed resemblance to Evelynn but it was obvious that it wasn’t her; the eyes smiling at the camera were a different color, and her hair seemed a different color too.
From her back pocket she drew a folded piece of paper, an article rudely torn out of a newspaper. She unfolded it and placed it on the bottom of a stack of articles that was already on the table. The article on top of the stack showed a family portrait containing both Evelynn and the girl in the photo next to her bed, as well as a man and a woman that must have been their parents.The headline read ‘Family wiped in suspicious fire.’
There was a map of the city pinned onto the wall between the table and the mattress. Several locations had a red circle around them with a number next to it. Next to the map, on the wall, was a list of names written with the same red marker, also with numbers next to it. Some of the names were crossed off. She crossed off another after which she dropped herself onto the mattress. A black cat jumped through the broken window.
‘Hey Shadow,’ she said. The cat meowed in response and curled up in her arms. She stroked it until she fell asleep.
