<!DOCTYPE html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /></head><body>ACT ONE: QUOD ERAT FACIENDUM

Four weeks have passed since Megan Jay was incarcerated. With Megan’s consent, Nicky Q. has taken over the operations for the time being. After the rocky start the Black Dragons have a hard time coping with the current situation. Valerius Aetius’ attempt to bribe Malcolm Winters of the Red Lotus had proven successful, though the rest of their take-over plan had more backfire than anticipated. After Gregory Dermoni’s sudden departure from the gang following the death of his daughter, Malcolm had been the only leader left and was tasked with finding a new co-leader. Valerius took that job, and the obligation to assign a new co-lead arrived for him too, just two days into the new job after Malcolm’s dead body was found in his office with his face in a mountain of cocaine.
The inauguration of Rose Ivy as Valerius’ co-leader caused a lot of controversy and dismay. It was unacceptable that she was a female; the rules of the gang clearly stated it were to be two male leaders – at least, up until Valerius changed that. Furthermore, she was a known Black Dragons member, unlike Valerius, who was only rumored to be. Rose was the head of PR for the Dragons, however, and despite the obvious advantages for the brothels of the Lotus it was simply not-done for a Dragon to be part of the Lotus, let alone as leader.
This caused a deviation within the Red Lotus, making the take-over a lot less seamless and effective. A group of Lotus members including two generals have secretly formed a new gang, named “The Wither.” Their sole purpose is to restore the Red Lotus to its proper glory and destroy the Black Dragons. Valerius and Rose do whatever is within their power to find members of The Wither, as they are both a PR disaster and a real danger. They dishonor the peace treaty and openly attack Dragons or pose as Dragons and attack the Lotus, causing wounded and dead, and spreading fear.
Among the dead was Estella Valdez. After a carefully planned ambush by the Wither during a Dragons exploration mission under the New Hope Hospital, Estella and her twin sister Karyme were found in one of the hospital’s dumpsters. Though Karyme still had a pulse at the time, she succumbed to her wounds a few days later in the intensive care unit. Tom Bankers, who was with the Valdez sisters, has not been seen since.
Following the disappearances and random attacks, Joshi Sandeep created a mobile tracking application for the Dragons, that Nicky made mandatory equipment during all missions and preferably outside it, too. A team was assembled at the Dragon’s Nest to monitor the activity of their active members. Most active assignments have been put on hold, both because of the Wither activity and Megan’s incarceration. 
On a brighter note, Layla and Daisylisa, the younger sisters of respectively Nicky and Megan, seem to be bonding well. They reside in the Aetius mansion with Thirza. They had been given a whole wing to themselves, which meant they barely saw Valerius or his wife Carine at all. Jeeves, however, came by multiple times a day to bring food and drinks, clean the place, or cater to the girl’s needs in any other way.
Now, almost a month after Megan’s arrest, the city is growing restless as her trial approaches. Despite Thirza’s best efforts to convince her otherwise, Megan has decided to not use a lawyer. She persists to her own defense, saying ‘that’s more badass.’ Many members of the Black Dragons had gathered at the court hall and so had some of the Red Lotus, all armed to the teeth and well aware of potential members from the Wither being present. The atmosphere was tense and more loaded than most of the guns as the trial began.
</body>
