<!DOCTYPE html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /></head><body>ACT TWO: ONLY THE DEAD TRULY REST

At the bottom of the hill Tom ignored the traffic lights and crossed the empty junction. He paid very little attention to the road which could be dangerous but at this time the streets were strangely empty for a city this size. He still hadn’t made up his mind on what to do with what Karyme had told him, but it seemed to matter very little, his hands on the wheel seemed to know what to do and they led him to the Black Dragons HQ. He parked in front of the building but hesitated to get out. Was this truly the right thing to do? It would have been easier to just send Karyme to Megan, let her do her story there. Sure, that would mean he wouldn’t get the honor or preventing a political murder but at least he wouldn’t have to worry about stuff like that. But given Karyme’s past she couldn’t be trusted, for all Tom knew her story had been an attempt of letting him get her to Megan to kill her. She wouldn’t have lied to him; after all she could have planned that with Gregory. Yes, he would have to ask her about that later.
He burst through the doors, half because he was slightly pissed off because this was ruining his moment of pleasure after the bombing and half because he had never been a subtle guy.
There were some people on the first floor who greeted him, but he ignored them. He had no time for being nice now. He climbed three sets of stairs loudly and banged on the door of the main office in the top. It opened almost at once, though it was not Megan or Thirza to open it.
‘Bankers,’ said no other than Valerius Aetius. Tom did not like Valerius, as he was dark, had a sinister sense of humor and above all did not acknowledge the authority of Tom or any of the other Generals. On the contrary, Valerius had the habit of acting like he was a General himself, even though he led no legion.
‘Aetius,’ Tom answered coldly.
‘I saw what you did to the storage boxes, you must be proud of yourself. I was just taking my leave.’  Valerius awaited no reply but slipped past Tom and vanished off the stairs. Now even more enraged, Tom marched into the leader’s quarters. Megan sat in a huge, black chair and as her hair and clothes were black as well she was hard to notice at first. Thirza sat on a table on the side in between two bookcases, her back against one and the bottom of her feet against the other. She seemed absorbed by a thick, leather-bound book and paid little attention to the others in the room. Megan tidied away some files into a binder and put it in one of the drawers in her desk. There was an open laptop on her desk which was connected to her phone, but she ignored them both. Instead, she looked up and smiled faintly.
‘Tom Bankers,’ she said. ‘I thought you would still be looking at your fires by now, what brings you here?’
‘Somebody pissed in my beer,’ Tom said. Thirza looked up from her book, confused, but Tom did not explain any further.
‘Listen, Karyme told me she overheard Gregory plotting to kill you, tonight.’
‘What?’ said Thirza with a high pitch, she seemed shocked. Megan, however, didn’t even flinch.
‘Yes, I know,’ she replied. ‘Well, sort of. He sent an e-mail to one of his members which crossed our servers and said something about striking the Dragons where it hurts them most’ She glanced at her laptop.
‘You knew this?!’ said Thirza with an even higher pitch. She jumped up, leaving the book on the table and walked over to the desk.
‘Well, I knew something was going to happen but it strikes me somewhat as a surprise that he’s after my life now.’ Tom noticed Megan seemed to avoid direct eye-contact with Thirza, though that was a common thing for Megan to do with anybody.
‘He mentioned something about a bed in the e-mail,’ continued Megan. ‘Being the owner of more than four-fifth of all the whores in town I assumed it was something with that.’
‘He’s gonna kill you in our bed?!’ Tom wondered how much higher Thirza’s voice could go before only dogs were able to hear it, but decided it was better not to ask.
‘You’re excused, Bankers. You did well,’ said Megan. ‘I didn’t think you would check back in today so I send Joshi the new tasks. You’re either gonna stop a Lillith export truck, Phoenix import ship or another empty warehouse. Joshi knows more.’  She put her focus back on her laptop and seemed to ignore her girlfriend. Tom left, slightly disappointed, but at the very least not disgraced.

<i>Gregory Dermoni waited in a parked car across the street of Megan’s house. She had entered the house around 2am, with Thirza and Valerius. Valerius had left at 2.30 and most of the lights had gone off except for the lights in the master’s bedroom. He cocked his Walter P99, making a remark about its fine German quality that no-one would ever hear, and slowly got out of his car. He kept a close eye on the lit window as he crossed the street, aware that his plan would be blown if either of the girls would bother to look out of the window. He climbed the steps to the porch and put his back against the wall next to the door, listening carefully. The night was quiet.
One of his spies had managed to get him a spare key and the alarm code. He was distrustful of their efficacy, but the key seemed to function and the alarm lit green after he put in the code. He considered himself lucky.
Gregory walked to the end of the hallway but stopped at the bottom of the stairs, again listening carefully. He hadn’t closed the door behind him; the sound of it shutting could alarm the girls.
The steps of the stairs were coated and Gregory may have been slightly overweight but he managed to ascend the steps quietly and unnoticed. It all seemed too easy.
The staircase ended in the middle of a corridor. It was unlit, but one of the lights on the street shone onto the ceiling, slightly lighting the place up nevertheless and the bedroom door was ajar, showing Gregory where to head.
He proceeded towards the bedroom, holding still as he reached its door and peered inside.
There was a pile of black clothes on the floor, unmistakably belonging to Megan, and a pile of more colorful clothes not far from it which must be Thirza’s. He opened the door a little further, carefully, and saw Thirza’s on one of the pillows with her eyes closed and a satisfied smile on her face. Her body was hidden under the blankets but he could make out the outlines and noticed a second bobble beneath the sheets, the size of a small human, between what should be Thirza’s legs.
Gregory pushed the door open even further, showing himself. The door creaked, Thirza opened her eyes and her smile faded as she pulled the sheets up to her chin. She seemed shocked as he raised his gun.
‘You don’t want to do this, Gregory,’ Thirza said. She seemed scared, but unsure about what was going to happen. The bobble between her legs moved slightly, but she paid no attention to it.
‘Oh, I think I do,’ answered Gregory, aiming at the bobble. ‘But I’m not here for you; I may even have work for you if you get a little older.’ He smirked.
‘You don’t know what you’re doing, Gregory,’ Thirza warned once more.
‘Trust me, I do.’ Gregory fired six, seven times at the bobble between Thirza’s legs. The white sheets turned red and the bobble stopped moving. Satisfied, he turned around and left the house.</i>

</body>
