ACT SEVEN: MOULDING THE KEY (PART THREE)

<i> ‘Get to cover!’ The entrance doors burst open and Roe’s team found itself in a rain of bullets. Four Phoenix members with heavy machine guns had entered the building, firing at everything dead or alive, piercing the wooden crates, concrete walls and metal pillars with bullets. Her team had obeyed quickly and kept low, covered by whatever they could reach. Dylan had found shelter behind on of the thicker pillars, firing at the Phoenix member whenever they needed time to reload or appeared to be shooting in a different direction. Paul was lying on the floor, stretched out behind a set of crates, using the same tactics as Dylan did. Laure had run for the office and was now out of Jennifer’s sight, probably hiding under the desk with Martin. Ilja and Gerdriaan were crouched, Ilja in the office as well just behind the doorway, firing a set of bullets every now and then, and Gerdriaan half behind a pillar and half behind a crate doing exactly the same. Jennifer dragged Haydon behind a set of crates as well, taking two bullets to her back in the process but as she was wearing a bulletproof vest as well it didn’t damage her much.
Jennifer left the fighting to her team and attempted to bring Legionist Haydon back to life.
‘Sandeep, can you get any Intel on Stephanie and Thomas?’ she asked.
‘I’ll see if I can get any image of them on the city’s CCTV circuit,’ he replied. Jennifer proceeded to give Legionist Haydon hands-only CPR, as a defib-unit wasn’t within reach, humming a song from the Bee Gees to get the right rhythm and pace.
‘One down, three to go,’ said Dylan, who had the best view on the situation.
‘Shit, I’m hit!’ yelled Paul as he retreated a bit further. Ilja ceased fire and ran to Paul to help him.
‘Two down. They’re retreating,’ updated Dylan. He and Gerdriaan headed from cover to cover, farther towards the door to keep the Phoenix from gaining ground.
‘Ilja, assist Dylan and Gerdriaan,’ Jennifer commanded. ‘Laure, Martin, attend to Paul and Legionist Haydon. Sandeep, gimme good news.’
‘I can’t, Roe. I got visual on Stephanie and Thomas, they’re disarmed, on their knees at the edge of the roof with their hands on their head and a gun aimed at them. They’re alive though.’
‘I suppose that’s something. How’s the ambulance?’
‘Driving around back, General Janssen’s behind the wheel with Legionist Collins as back-up.’
‘We stole an ambulance?’
‘Yeah, figured you could use a lift outta there for the cargo too.’
‘Brilliant, thanks.’ Jennifer carried the oxygen tanks to an empty crate, put the wetsuits in as well and dragged the crate to the backdoor.
‘Joshi, what’s the situation in the street?’ Jennifer asked, as her team no longer seemed to fire bullets.
‘Looks like they encountered more resistance than they anticipated; no Phoenixes left on the street.’ Jennifer took off the bulletproof vest and gave it to Laure.
‘Take this,’ she said, ‘and head outside to draw their attention. Gerdriaan, help Martin to get Paul to the backdoor and into the ambulance once it’s here. Legionist Collins will help me with Legionist Haydon here. Dylan and Ilja; go around the back and head up to the roofs to support Stephanie and Thomas, and by the gods make sure they’re not pushed off the building.’ Jennifer’s team obeyed at once, Laure put on the vest and ran outside firing her magnum into thin air while Ilja and Dylan opened the backdoors and ran for the fire escape. Seconds later the ambulance reared into position and Legionist Collins opened the back from within.  Martin and Gerdriaan carried Paul into the ambulance while Jennifer and Legionist Collins got Legionist Haydon in. Gerdriaan carried the crate to the ambulance, fitting it in with effort, while Martin sat down in the passenger’s seat. Legionist Collins closed the ambulance doors and the ambulance drove off without him.
‘I’ll secure the ground level,’ Legionist Collins shortly said. ‘You go help your team.’
Jennifer ran for the fire escape as well and made her way to the rooftops, making sure she wouldn’t be spotted.
‘Stay low,’ she told her team. ‘I got this.’
It seemed the Phoenix had been surprised by the Dragon’s thorough preparations and most of them had backed off, leaving only one man behind to keep both Stephanie and Thomas aimed at. He seemed nervous, switching target each second even though Stephanie and Thomas both did what they were told to do in case an event like this occurred. They were told to remain calm, not to try anything, no sudden movements, and above all not to piss the gunman off. Both of them looked at the ground, terrified, their feet dangling over the edge. They didn’t see Jennifer coming which was a good thing, as any spark of hope in their eyes could set off the man holding the gun.
Laure was firing her gun evermore, helping Jennifer not to be heard as she approached the Phoenix’ gunman. The light was in her favor too, her shadows were behind her. She quietly sneaked up to the man, at once pushing the arm in which he held the gun up with one hand and placing her other arm around his throat.
In a reflex the man fired the gun and screamed for help. Thomas fell over and Stephanie screamed. Laure stopped firing her gun and yelled ‘what happened?!’ from below while Jennifer managed to disarm the Phoenix member. She squeezed his throat tighter and he lost consciousness.
‘Dylan, Ilja, carry Thomas down. He’s not dead, the shot didn’t hit anything. He just fainted. Steph, get a hold of yourself; we need to get out of here. This guy ain’t dead, he’s just unconscious. Laure, you did good, now make yourself scarce before the Phoenix get back-up.’
‘There’s a green Seat at the bottom of the fire escape, Roe. It’s unlocked and the keys are inside, it belongs to us. Use it to get Thomas out of there,’ said Joshi.
‘You heard the man,’ said Jennifer. ‘I’ll drive.’</i>

There was a red Alfa Romeo Giulietta parked across the street from Megan’s house. It had the Black Dragons emblem spray-painted across its hood, seats of white leather, red tinted windows and sports tires that had been replaced recently. It was not an uncommon sight in this street, the car stood there more often and always at the same spot and always with the same driver, alone in his car. Today, however, Tom Bankers sat in his car with different feelings.
He looked at the house; it seemed as innocent and motionless as ever. All the curtains were closed, as were the windows, as was the door. The driveway was empty, but that too was not uncommon at this hour. Tom hesitated to get out and walk up to the house. Not because he never went up to the house, today was different anyway, but because the inside of the house held answers. Answers were good, answers meant intelligence and Intel meant power but rumor had it Megan was dead and if that was true – Tom tried not to think of it.
He slowly got out of the car, quietly closed the car’s door and locked it. He looked both ways twice before crossing the deserted street across the driveway and onto the porch. The door was not locked and the alarm not enabled; Tom had free play as he entered the house and even though he did not expect to be interrupted, he closed the door.
He heard a gasp upstairs. Alarmed, Tom drew his handgun and slowly approached the stairs. Quietly, very quietly, Tom ascended the stairs, pausing at each step to listen carefully but there were no more sounds.
At the top of the stairs, he noticed the bedroom door was ajar. He knew this was the bedroom door because of the many times he had spent in his car keeping an eye on the house and the people in it, especially Megan, by no surprise.
He opened the door further with his right foot, his gun aimed and at the ready only to reveal the aftermath of the night before. 
The Red Lotus’ whore Loja Makaine sat in the middle of the bloodstained bed. She’d thrown the sheets on the ground and embraced the body, which Tom much to his relief knew was not Megan, but moreover a girl he did not recognize. Loja seemed to recognize her all the more, however, to such a degree that she didn’t seem to care at all that she was found by a member of a rival gang on their property, with a gun at her head. Tom realized the gasp had been because Loja had found the girl rather than that he had entered, and lowered his gun.
‘I didn’t mean for this to happen,’ said Loja. She looked at Tom but her eyes were so full of tears that he wasn’t sure if she recognized him at all. ‘To be honest I didn’t think anyone would die, I thought if I’d tip off the Dragons they’d do something,’ she added.
‘They did do something,’ Tom replied, trying to hide how happy he was that his Megan was still alive somewhere. Loja’s eyes flashed with anger.
‘Something?! They had Gregory shoot his own fucking daughter and he wasn’t even aware of it. Emma was sixteen, for fucks sake, she shouldn’t even be involved with any of this, not involuntarily, and not at all to be killed by her own father.’
‘Weren’t you fifteen when you started?’
‘Exactly my point; look where I ended up.’ Tom looked at Loja, his eyes sliding down from her face to her breasts, where they paused, after which they slid down further to Emma’s head. Emma had been bound tightly; Tom could see blood had dripped from her wrists and ankles and the corners of her mouth where the ropes had held her. Her hands and feet had been tied together by the same rope, twisting past the entirety of her body, but they had used a different rope for her mouth, to keep her quiet. She had probably been drugged heavily as well, Tom realized.
‘Whatever,’ he said carelessly. ‘I got what I wanted, I’m out of here.’
Tom left without another word, deciding to take the rest of the day off until eight.

