ACT NINE: MARE NOSTRUM (PART TWO)
<i>It took the trio near forty five minutes to reach The Avalon Affinity. After half an hour Nicky’s now untreated wound had taken its toll and she could no longer keep herself afloat. Much to her dislike she had spent the last fifteen minutes being dragged onwards by Danilo and Jennifer, who with great effort managed to get all three of them to The Avalon Affinity where Valerius was kind enough to help them aboard. The Avalon Affinity was a large sailing yacht and felt a lot more luxurious than The Little Seraph, which was a mere small motor yacht.
‘Welcome to the AA,’ he said as he stretched his arm and pulled Nicky in. Danilo and Jennifer managed to get onto the ship by themselves. The three observed the yacht in admiration.
‘If this is the AA I won’t mind another DUI,’ Danilo said. Valerius grinned, Jennifer threw an angry look in Danilo’s direction and Nicky seemed confused. Her confusion lasted only shortly, however, as her wound now seemed to hurt her so much she could barely keep standing. She lost her balance and fell over but Valerius had a quick reflex and was still near her, and caught her.
‘What’s up with her?’ he asked rather surprised.
‘Flesh wound on the shoulder. She had it bandaged but we used the bandage to trap the Jericho.’
‘Take one for the team, did she?’ Valerius said admirable. It was not a common gesture among the gangs to sacrifice your own wellbeing for the sake of the mission or the sake of others. The people were too selfish for that. Sure, they’d pretend to help out or be there for you, but when shit got tense it was always the each-for-himself-code that was honored. He knew a less than handful number of exceptions to this rule, but apparently Nicky was one. He would remember that. Nicky had now lost her consciousness and Valerius lifted her fully.
‘Listen, I’ll take care of this, take her into the cabin and patch her up. You both don’t need to worry about that. Why don’t you two head up to the bridge and meet Jeeves, and tell him to set sail for home.’
‘I saw you looking at her,’ said Jennifer as she and Danilo climbed the latter. ‘That better has been concern on your face and not you getting all horny.’ Valerius laughed at that as he entered the below deck, carefully, to make sure Nicky didn’t hit any walls.
The yacht was big; it had a living room with an open kitchen, separated from the bedroom in the front. Valerius entered the yacht through the living room, as that was the only way to enter, and was making his way through the room.
‘Who’s that?’ asked no other than Megan J., the girl thought to be dead by the Red Lotus and even a few within the Dragons. She sat on the couch with her laptop on her lap and her phone next to her. Valerius had been carrying Nicky in such a way that Megan could see no more of her than her feet and maybe the tip of her hair.
‘It’s Q.,’ answered Valerius without looking at Megan. He moved on to the bedroom and laid the girl down at the moment the ship’s engine started up and the ship started moving.
Megan had jumped up and followed him, both because she and Nicky had a close bond and because she figured Valerius would need help. The latter proved itself true right away as she unzipped Nicky’s wetsuit while Valerius kept Nicky up. Together they rolled the wetsuit back slowly, inch by inch, and careful not to make matters worse. As they reached the wounded shoulder, however, they came to realize there was no way of getting the wetsuit off without ripping the wound open as the blood had solidified and had glued the wetsuit to her flesh. They had no choice but to pull it off, however, and soon Nicky’s blood flowed yet again. They rolled the wetsuit down until just beneath her shoulders – it would feel wrong to uncover her boobs, and as her shoulders were bare they could not be sure if she was still wearing anything beneath the wetsuit.
Valerius and Megan functioned as a dream-team on that moving vessel. It were four hands on maybe five square inches of body but they were never in each other’s way. The med kit from under the bed had been put next to Nicky’s head and Megan disinfected the wound as Valerius prepared the cotton gauze. Then, as Megan applied the patch, Valerius looked for the right bandage and prepared it after which he carefully lifted Nicky’s upper body so that Megan had all the space she needed while she applied the bandage too. The entire procedure took roughly ten minutes, after which the two took a moment to admire their teamwork. Nicky was still unconscious, however, so they decided to let her sleep for now and covered her with the blankets.
‘I’m gonna call a doctor,’ said Valerius as they had left the bedroom and Megan sat back down on the couch with her laptop. Valerius headed back into the bedroom to have his phone conversation in a quiet room right as Danilo entered.
‘Jeeves told me you’re here,’ he told Megan. ‘Whereas Karyme told me you’re dead.’
‘Remarkable how an outsider’s Intel can be more reliable than an insiders’, isn’t it?’ Megan replied without looking up. Danilo drew two cans of Mt. Dew from the fridge and gave one to Megan.
‘So what are you gonna do about Bankers?’
‘I’m not sure yet,’ Megan admitted as she closed her laptop and looked at Danilo.
‘If this is true regardless his intentions, he deliberately declined a near fail proof plan and risked the lives of three allies in a bold move. It’s weird, though. I mean, he does carry the gang’s tattoo twice. You would think that’s a sign of loyalty, but his recent actions seemed more a sign of betrayal.’
‘He’s changed, hasn’t he? I wonder what got into him.’
‘Maybe Sandeep’s intelligence pissed him off. It’s not uncommon for smart people to get annoyed by the intelligence of others.’
‘Maybe Karyme told him too about you being dead.’
‘You know, that could very well be it. He could be convinced I’m dead and become reckless and inconsiderate. I’ll have his story before I do anything either way, but putting the life of allies at risk without reason is serious.’
‘I trust you’ll make the right decision.’ Danilo looked at the bedroom door.
‘How’s Nicky?’ he asked.
‘She’ll be okay.’
‘Listen, man, you gotta do something extra for her or something. She practically sacrificed herself for the mission.’
‘I’m aware of that,’ Megan replied. She had her laptop open once again and redirected her attention to it.
‘Why aren’t you with Jennifer on the bridge?’ she asked as Danilo attempted to sit down but decided not to as the wetsuit made it rather impossible. He was now just awkwardly standing around drinking his dew.
‘She’s mad at me, says I looked at Nicky too much.’
‘Can’t blame you,’ Megan admitted. ‘She didn’t look too bad. Not as good as Thirza looks in a wetsuit though.’ She looked at him daring and added ‘I’d know.’ Danilo’s jaw dropped as the image slid into his mind, but he shook his head and changed subjects.
‘Why did Karyme think you were dead?’
‘Karyme was misinformed, simply said.’ Megan closed her laptop again right as Valerius came back into the room. ‘She was right that there had been an attempt to kill me that night, and her source wasn’t faulty either. Gregory Dermoni entered my house and killed without checking his target. Thinking it was me, he returned to his office cheerfully and told people about what he’d done. That spread and reached Dragon ears.’
‘So what did happen?’
‘Gregory killed his own daughter,’ Valerius said.
‘We had Emma kidnapped for weeks and were negotiating with the Lotus on a peace treaty. We weren’t bad to her either, we fed her properly and she was allowed to call her parents about her wellbeing. Of course, with a gun to her head so she wouldn’t say anything important, but nevertheless her parents knew she was fine. We would’ve given her back this weekend if Gregory hadn’t tried anything.’
‘But he did try something,’ added Valerius. He seemed amused with the story and tried to hide a smile.
‘Right,’ Megan continued. ‘We got word from a Lotus whore that Gregory had plans to assassinate me. Luckily, we got spies high up the Lotus ranks so we rather knew his exact plans. Thirza came up with using Emma as bait as we were keeping her in my basement which meant she could easily be used unnoticed. Aetius helped us to tie her down and drug her after which we carried her to the bed and put some clothes on the floor to make it look like we were “having fun,” if you know what I mean. That was also Thirza’s idea by the way. Thirza put on a bulletproof vest and got in bed with Emma, had Emma between her legs and did some fine acting when Gregory came in who shot Emma half a dozen times and left.’ Danilo’s face expressed a mixture of admiration and shock. Jennifer had apparently been listening from behind the door hoping for some kind of confession from Danilo and entered the room now, also visibly shocked.
‘So now what?’ she asked. Valerius passed her and went outside.
‘We’ll see. We do know Gregory found out about Emma earlier today. No doubt he filed the murder with the police who will be checking all addresses associated with me right now. Let’s hope they’ve already gone by the Aetius mansion by the time we get to land.’
‘Which is in about five minutes,’ Valerius announced. ‘It’s a pity that it’s dark outside, my house looks amazing from the sea.’

They did catch a glimpse of the house as it came into view, however, as it was lid up in flashes of red and blue. A police car was standing in Valerius’ backyard, with police chief Adessi sitting patiently on its hood accompanied by one of his colleagues. The crew at the ship had gathered at the bridge, all but Nicky of course, and observed the car as they approached the boathouse.
‘Good thing I had the backyard paved last month,’ Valerius noticed. Jeeves held in.
‘How do you wish to proceed, sir?’ he asked. Jeeves was Valerius butler, next to Megan the only person Valerius knew he could trust fully, and he knew Jeeves would follow his every command. But as the police wasn’t there for him, he wasn’t the one to call a command.
‘I’ll leave that up to Megan,’ he said instead. ‘I believe Adessi’s here for her.’
‘I believe so, too,’ she answered. ‘No change of plans, though.’ 
Nicky woke up as the engine silenced and the boat was docked. Jennifer helped her get the wetsuit back on, by a lack of anything better to wear, and together they marched up to the mansion and the police car. 
‘What’s this, Adessi?’ Megan asked when they were level. ‘We paid up this month.’
‘I’m here to arrest you, girl,’ Adessi answered. ‘For the murder of Emma Dermoni. We found her body in your house, shot seven times.’
‘You ain’t taking her on my watch,’ said Nicky. She swiftly drew Megan’s gun from her holster and aimed it at Adessi.
‘No, it’s okay,’ said Megan. ‘I’ll go along. I’ll be back out in no time.’ Her hands were cuffed behind her back and she got in the back of the police car.
‘Aetius: tell Thirza that Judas came by,’ she said mysteriously through the open window. Valerius nodded and whispered something to Jeeves who then entered the house. The police car drove off, with Adessi smiling broadly and Megan winking at the group before the car reached the corner and drove out of sight.</i>

