ACT ONE: A DIRE SHADE OF RED

Tom stood on one of the hills just south of Letum with Rose and Ramiro. The hill belonged to the Ivy family and as he was in the presence of the sole heir to the Ivy legacy, Rose Ivy, he could access it which seemed moreover useless, but had a theatrical touch that he liked. It was a high hill and looked out over most of the city, which meant he could observe it, and admire his own creations when the bombs went off. It was getting dark, which made the sounds from the city seem all the louder and he followed the lights and sounds of the sirens as they ran through the streets all headed for that one building near the harbor.
It had been a simple job. Too easy, really, and Tom had been reluctant to do it but it had been a task specifically assigned to his legion by no other than his leader, Megan, and Tom was prepared to do just about anything for Megan even if that meant blowing up a seemingly abandoned building. Besides, Tom liked to blow up just about anything and it had been a good opportunity to teach his Legionists some more.
He had decided to only involve Rose and Ramiro during this job. Rose had been involved with the building process of similar buildings and knew some interesting details about its construction and Ramiro had a determination to properly and carefully execute every task, which means he was on guard even if he was almost certain there wasn’t another soul in the building.
The building they were to blow up had been a storage unit that belonged to the Red Lotus. It was usually used to stash drugs or alcohol that was meant for merchandise, but their business had gone downhill lately and many of their storage units were now empty. It was the reason Tom had protested at first to blow it up. He had suggested they blew up something that was in use, instead. But Megan had insisted, she said it was about sending a message to the Red Lotus. Besides, the fact that the lot was empty meant they could do more with it. One of the other Generals had prepared the place, stacked it with kegs of gasoline, which made for a nice bonfire.
Ramiro had prepared the bombs, supervised by Tom himself. Rose had pointed out that there were six pillars supporting most of the structure, which meant that if those were blown to pieces the building was sure to come down. Rose and Ramiro had gone into the building together, carefully placing the bombs and charged them with an LPD, Long Period Delay Detonator, which would ensure their safety by giving them enough time to leave the building and vacate themselves from the area. Tom had waited outside the building with the getaway-car. He had been the only one to see their work explode, in the rearview mirror of the car, as they drove out of the city and onto the hill they were now standing on.
The police had been the first to leave their stations. They had been standing on the hill for about five minutes when the first sirens sounded and the police cars left. The fire brigade needed ten minutes more to get en-route, but they were a lot closer to the crime scene and arrived only six minutes later than the police. Tom kept track of it all, and was disappointed that it took them so long.
Mesmerized by the fire and the business around it, the trio failed to notice two headlights slowly climbing the hill. It wasn’t until the car door slammed that they noticed its presence. It was no enemy, however, but an ally. Karyme Valdez had entered the scene.
‘General Bankers, sir,’ she said with effort. She was breathing heavily and seemed worried.
‘What is it?’ Tom asked calmly and unmoved. Karyme was a decent girl, and good looking too, but she’d had a long history within the Red Lotus gang and therefore Tom simply could not trust her.
‘I was just in the Sexy Stuns,’
‘You in a brothel, why am I not surprised?’ said Ramiro.
‘Oh shut up,’ Karyme snapped. ‘They’re planning to assassinate Megan. I overheard Gregory talking with some others; they’re planning to kill her tonight.’
‘Thanks for letting me know,’ replied Tom. ‘You can go now, and take El-Hashem and Ivy with you.’ He turned back to look at the fire, listening to the sounds of the three others getting in Karyme’s car and driving off. He was unsure how to proceed, unsure even of what to do with the information. He knew he had reasons to distrust Karyme, but if she had the same determination to prove her loyalty as her sister did, she would think twice before attempting to make him look like a fool with the leader. Also, could he really take the risk of not taking this seriously? Shouldn’t he in theory be doing whatever he could to prevent the leader, his leader, and let’s not forget also secretly the love of his life, from being annihilated?
Tom got back in his car. The firemen were still fighting his fires as he drove down the hill, unsure where to head next. He couldn’t go after Gregory; the city was big and he had no idea where Gregory was now. He could go home; discarding what Karyme had said as unimportant or untrue, knowing that if Megan would get killed he would have that on his conscience too, or he could go to the Black Dragons’ HQ where he knew Megan was, to inform her of what he had been told, risking his dignity as he would look like a fool if the rumors appeared to be lies.

