ACT FOUR: SHADES OF SERENITY

<i>Karyme Valdez knelt at her mother’s grave. She had received a text message saying that Megan J. was dead, and she’d found herself overcome by fury and sorrow. She was mad at Tom; she thought that he would do whatever was necessary to ensure Megan would survive. She was mad at herself; she shouldn’t have gone home after telling Tom but should have headed to the headquarters instead to tell Megan herself what she had heard and she even felt a little fury towards Megan for failing to survive even though she could have been prepared and for abandoning her and the guild and just leaving everybody behind like that, just like her mother had done. It had been three years since her mother had died and buried in the Serenity Cemetery and Karyme hadn’t visited the grave ever since. She had never felt the need to; even though Megan was three years younger she seemed a whole lot more mature and had almost felt like a second mother, or at least fulfilled the need for one, but Megan’s passing had reminded Karyme of her mother’s passing and she found herself back at her mother’s grave after three years of avoiding the confrontation. Karyme had brought no flowers, but that was an uncommon habit anyway, so instead she knelt in the grass that separated the dusty gravel-paths from the graves and she shed a single tear.
She liked the Serenity Cemetery. It was one of the three no-war zones in the city, the others being the New Hope Hospital in the north and the St Mary’s Cathedral in the center. The cemetery was built on one of the hills on the west side of the city and just outside the city limits, looking out over the sea which made for nice sunsets in the evening. It was a quiet place, and even enemies greeted each other with respect within the cemetery gates because everybody knew that coping with a loss is hard, and requires strength. It was written in the rules of every gang that fighting in the no-war zones was to be avoided at all costs and everybody obeyed these rules of respect.
Coincidentally, these no-war zones were also the location for most of the inter-gang meetings. And thus, Loja Makaine paced her way across the gravel. She slowed her pace and quieted down as she entered the isle Karyme was knelt in, to patiently wait at a respecting distance. It took Karyme a few more moments to get up and acknowledge Loja’s presence and Loja saw her face was wet with tears.
‘I’m sorry,’ said Loja during a short embrace as Karyme had walked up to her.
‘It’s not your fault,’ said Karyme after they broke up their embrace. ‘You did what you could do, and we’re only pawns in their game.’
‘Still, I could’ve-
‘Could’ve what?’ Karyme interrupted. ‘Could’ve stopped him? You’d endanger your own life, if Greg wouldn’t get you for it the rest of the Lotus would for treason just like they went after Estella and me. You did your best; you did all you could do and its Tom’s fault it didn’t pay off.’
‘Well, well, well,’ Said Valerius. He had approached the girls without their awareness. He was good with the shadows, even if there were none. He had walked on the grass to avoid making sounds on the gravel. He carried four colorful bundles of flowers which contradicted his overall dark and sinister appearance. He made no effort of hiding them, however, both because he knew there was an atmosphere of respect and because he generally seemed not to care a lot about what people thought of him.
‘Hating on your General, are we? With a Lotus, no less. I guess that explains a certain amount of Intel miracles.’
‘Loja,’ Loja said, lifting her hand to shake.
‘I know,’ said Valerius. ‘You have a name around town, Miss Makaine.’ He did not shake her hand, nor made any attempt to justify his behavior.
‘In any case, I think you’re being naive, Miss Valdez. I thought you knew better than that. Second hand sources, as trustworthy as they may be, are not always reliable. Do you believe in ghosts?’ Valerius smiled at the looks of confusion that had appeared on the girls’ faces.
‘Makaine, Valdez.’ He nodded at them as he passed the girls and continued his way to a large, white-marble family grave in the back of the cemetery.</i>
Meanwhile, Tom Bankers had granted himself a few hours of sleep and made his way to Danilo’s apartment, which wasn’t too far from his own. He came in to find Danilo asleep on the couch beneath a dozen of maps he had pinned on the wall. They showed specific parts of the city, its harbor and most of the seas around it, complete with the depths of the sea. It had a thick red line, drawn with a permanent marker, from square E1 to C3, which curved around the city and ended in an X in the square next to the harbor, which was in D4. There were several additional maps showing a bigger version of this exact part of the map as well as a detailed map of the city which had a route marked with a red line as well.
Danilo woke up as Tom slammed the door shut, mumbling Jennifer’s name.
‘Good morning, sleepy head,’ said Tom. Danilo seemed not to appreciate it. ‘You’ve been busy,’ Tom added. Danilo looked unfocused for a moment then seemed to remember the evening before.
‘Night!’ he exclaimed. ‘We’ve got to move at night. Tonight, even. The ship moves in today but there’s no place in the harbor until tomorrow morning so it’s spending the night just off shore and that’s when we have to move. I suggest taking a team of four, you and me, and – oh I don’t know, Q and Roe I suppose would work well. They’ll only be using one of the engines to power the boat at night so we rig the others. Then, the following morning as they try to leave and power their engines…’
‘Boom,’ finished Tom.
‘Boom,’ Danilo confirmed. We can watch the whole thing from our yacht, pretending to spend the night with it not too far from their ship.’
‘You are a mastermind, Seuss.’
‘Thanks. There’s one problem though.’
‘And what’s that?’ 
‘Our yacht was stolen and you have to pick up the wetsuits form the warehouse in Phoenix territory. I know you’re good, but you can’t do both. And the bombs still have to be made too. We’ll have to split the team and meet at the docks in the evening.’
‘I’ll give Roe and Q a call from the car. If you could make the bombs while we sort out the rest, we’ll meet you at the docks at eight.’
‘Very well, General Bankers.’

Tom left the apartment and set back in his car, just sitting there with his hands resting on the wheel. His phone’s screen lit up, telling him he had 3 unread messages from 2 contacts. The first was from Megan, send a few hours ago. It read ‘Don’t buy it, they don’t know what happened.’
The other two were from Karyme, both only an hour old, about fifteen minutes apart. The first read ‘J=KIA. Xx KV.’ It took him a while to figure it out. Luckily, the second was a lot clearer and made him unsure how to proceed:
‘Aetius knows more.’

