<!DOCTYPE html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /></head><body>ACT ELEVEN: COUNTING THE HOURS

<i>It was still rather early in the morning when Thirza and Nicky arrived at the remand center where the delinquents were kept when awaiting their trial. Jeeves had been kind enough to drop them off but said he was too busy to join them inside. The visitors’ room was divided into two separate rooms separated by the line of booths with their phones and their glass uniting the inmate with their visitors but separating them all the same. There were a total of twenty booths, supervised by three guards on either side. Thirza and Nicky were told to go to booth seven and wait there.
Megan entered the inmate’s end of the room not much later. She looked different wearing a bright orange jumpsuit rather than the long black coat and her hair tightly bound in a ponytail rather than to have it loosely on her shoulders like she usually had it. She carried a disposable, plastic cup with too strong but merely lukewarm coffee as she casually walked up to booth seven, turned the chair around and sat down with one leg on either side of the chair’s back. She then sipped her coffee, grimaced, and picked up the horn on her side of the glass. Thirza and Nicky picked up their receiver too and held it in between them, with their heads close together so they could both hear what Megan was saying.
‘Good morning,’ she said rather bright. The situation did not seem to threaten her at all.
‘Morning,’ Thirza and Nicky choired.
‘How are you feeling?’ asked Nicky.
‘The coffee’s better than I anticipated,’ Megan answered. Thirza rolled her eyes.
‘When are you getting out?’
‘Patience, hon, I’ve only been here for like three hours or something. I’ll hear the date of the trial later today and I’ll make sure they let you know. Meanwhile, I trust the two of you can keep things running.’
‘I’m not even in your gang, Meg,’ said Thirza.
‘True and false. Either way, Nicky is, and I’m sure she won’t mind you hanging around as long as she is in charge.’
‘Wait, you’re putting me in charge?’ said Nicky surprised.
‘Well, yeah, as long as I’m locked up here you can be the interim leader. Don’t do anything irrational, just keep things running. If anyone asks questions just forward them to Thirza.’
‘Why not Aetius?’ Megan smiled before she answered.
‘He seems cut out for leadership, doesn’t he? He’s got other things on his mind though. Besides, he’d never accept it.’
‘Why me?’
‘I think you’re the best I got. I’m probably promoting you to General soon, too. Banker’s spot will be vacant soon. Frankly, I don’t even care what his story is. You can’t just put people in jeopardy if you don’t have to. There is no legit explanation for it. Depending on his story I’ll see whether he’ll be a Legionist or member, but he’ll lose General for sure. That’s future talk though; you just lead the entire gang for now. No pressure.’ Thirza seemed unsatisfied. Not because of Megan’s politics; she quite agreed that Nicky was the right choice here, but because she didn’t like to be separated from her love. Nicky still seemed to think Megan had been joking when putting her in charge. Nicky had never really been in charge of anything, after all, and that had always seemed to be the way things should be. Nicky served. Nicky obeyed. Nicky followed orders. Nicky did not give orders, and even after becoming Legionist she had avoiding working with her team as often as possible because, somehow, being in charge frightened her. The weight of caring responsibilities over others than yourself seemed a heavy burden even with only ten people beneath you. Now she had all twelve hundred, who knew for how long? Sure, Megan seemed to be confident in her innocence and suspected to be back out on the street within a few days but what if she wasn’t? It wouldn’t be the first time Letum’s justice system failed. Wasn’t that, after all, the reason the statue of Lady Justice in the courthouse was blindfolded?
‘How’s your shoulder?’ Megan asked, disturbing Nicky’s thoughts and breaking the silence.
‘Not too bad,’ she answered still glassy eyed. ‘You owe Aetius one for that.’
‘I owe him more than just one, trust me.’
It was at that moment when Mia Dermoni entered the visitors’ room, exchanged a few words with one of the guards during which they threw looks at booth seven a lot after which she marched over.
‘Excuse me,’ she politely said. ‘Might I have an audience with miss – eh, I don’t know her last name…’
‘Very few do,’ Nicky said as she got up. ‘We were just about done.’ Thirza kissed her index- and middle finger together and then held them up to the glass, synced with Megan who did the same from the other side. Thirza then got up too, throwing a look of anger and disappointment at Mia for cutting the time she could have with Megan. Thirza and Nicky left the room together.
‘Miss Dermoni,’ said Megan fearlessly. The fact that she was currently held captive for the murder of the daughter of the women sitting on the other side of the glass seemed not to bother her. It was by no doubt the reason for Mia’s appearance, though Megan was well aware that Mia was updated on the true course of events. If anything, the running mascara gave away that she had been crying recently.
‘I want you to take him down,’ she said very firm and determined. It seemed all her sorrow had translated itself into more anger and any sign of kindness or happiness had faded not only from Mia’s face, but Megan’s too. This was business.
‘I want you to take everything from him. His job, his money, his honor, his dignity. Not his life, though. I want him to suffer. I know you were involved and at first I was mad at you too and thought it served you right to be locked up, but you were only doing what seemed best, right? You never meant for Emma to die.’
‘I’ll admit in hindsight it probably would have been more profitable to have given Emma the bulletproof vest rather than Thirza. I don’t get his irrationality though, we were about to give Emma back. We were days away from a peace treaty.’
‘Yeah, Loja told me. That asshole’s gonna pay for this, mark my words. Either way, I don’t want just Gregory to go down. His entire gang, that Lotus business of his, it’s time we put a stop to that.’
‘I thought The Lotus were co-lead? Taking Gregory down is not going to destroy the guild either way.’
‘I know that, but I also know stuff that can really hurt them. The Lotus isn’t all that strong, they could fall before you get your trial if we play it right.’
‘I’ll see what I can do in court about Gregory,’ Megan told Mia. ‘But really, it’s up to the judge. As for the rest of The Lotus, you’ll have to see the Dragon’s interim leader for that ‘till I’m out of jail. There should be a black Mercedes showing up on the parking lot soon, talk to the driver. Just tell him what your problem is, he’ll make sure you get to the right place.’</i>

Meanwhile, Tom Bankers was still on The Little Seraph. He’d gotten a few hours of sleep and sat on the deck, enjoying the sun and awaiting the majestic explosion that would crown his work. He had been a little surprised that nothing had happened yet as he had send the team out with a mere three anti-tank grenades. He wondered if they had been caught but trusted in the assembled team’s expertise to get the job done. He was not disappointed; a little after 7AM the ship’s engines came alive, shortly after followed by a majestic bang which blew Jericho’s door out to open sea. Large holes had been blasted into both sides of the ship and the engine room had been thoroughly destroyed, letting hundreds of gallons seawater flow right into it. He heard people scream as the flames made themselves master of the parts of the ship that were not dominated by the cold, salt water while the rear of the ship slowly started to sink into the depths. Some of Jericho’s crew jumped overboard and tried to head for land but there was a lot of air left in the ship that quickly filled itself with water creating a suction that pulled them back.
Just when Tom had come to the satisfying realization that it could barely get any worse for the people on The Jericho, the ship had gotten so near to verticality that the pressure on the twist-locks and lashing rods had changed severely in a direction uncounted for. They snapped, releasing the containers they held which fell down taking crewmen along in their fall and crushing the crewmen or dragging them into the depths. Not much later the ship had completely vanished beneath the surface and the sea had returned to the restful state it had been before, as if nothing had ever happened. Satisfied, Tom turned on the engines of The Little Seraph and headed back to the harbor.
‘You again?’ said Tom impatiently as he made port. Valerius was sitting on the hood of his black Mercedes McLaren awaiting Tom’s arrival. Valerius seemed to enjoy the impatience and annoyance that Tom showed, or perhaps the anticipation of Tom’s near future amused him.
‘Hop in my car, Bankers, you have an appointment with the leader at the remand center.’
‘Meg’s in jail?!’ Tom exclaimed as he got into the car. It was good to be sure that she was still alive, but locked up was hardly any better.
‘Not for long, but that matters little.’ Valerius drove off.
The car ride was plainly awkward. Valerius drove the car with a smile on his face that did not predict anything good. They didn’t speak, nor was the radio turned on, but they drove in complete silence other than the sound of the engine. It was still early so most of the roads were deserted meaning the speed Valerius held was at least twice the limit but he had good control of the car and they arrived safely. As they pulled up on the parking lot a woman approached their car.
‘Alright, just head inside, talk to the guards, they’ll get you to J.’ Valerius said as he rolled down his window to talk to the woman. Tom proceeded towards the building. He threw one more glance at the Mercedes and saw the woman getting into the car with Valerius and he watched them drive off.
Megan was still sitting at booth seven when Tom arrived in the visitors’ room.
‘You’re lucky,’ Megan said as Tom had picked up the horn on his end.
‘Why is that?’ Tom asked.
‘Because the interim leader would have skinned you alive. What happened on that boat, Bankers?’
‘What do you mean “What happened on that boat?” I did my job, the boat went down.’
‘Why did you change the plan?’
‘You mean why didn’t I go with Sandeep’s plan? Sandeep wasn’t on that mission, I was. My plan was just as flawless as his was, I don’t see why either plan would make a difference.’
‘You put the lives of three allies in jeopardy, Bankers. You’re lucky I don’t have you killed for this. You’re having me doubt your loyalty.’
‘Doubt my loyalty? Need I remind you that I carry the gang’s emblem twice? Need I remind you that my car’s got the emblem spray painted on it?’
‘In the end that’s just an image, a meaningless image, if the fact that others carry it too doesn’t mean anything to you. You’re gonna have to come up with something to prove your loyalty. In any case, I’m taking the General rank off your shoulders. I’m degrading you to Legionist, and you’re lucky I’m not doing more. Think about what you did, we’ll see what happens to you when I’m out of prison.’ Megan put the horn back in its holder and one of the guards brought her back to her cell. 
‘Loyal?’ Tom angrily said as he got up and walked out. ‘I’ll show you loyal. I’ll show you what the emblem truly means.’

</body>
