<!DOCTYPE html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /></head><body> THE CITY OF LETUM - SOCIETY OVERRUN BY CONTROVERSY


Far into the fourth century AD, Roman emperor Theodosius the first constructed plans to for once and for all dispose of all criminals and wrongdoers that had threatened his empire or his citizens and were still alive.  On an island just off the coast, occasionally connected to land by a small strip of land if the tides allowed it, he had them build their own city, in which they could live as free men, unbound by law. The city was named Letum, which means death, decease or destruction in the Latin language. It was a small, self-sufficient society, consisting of mainly farmers and their families. The birth-rates were explosive, however, and the settlement grew quickly. After the western Roman empire fell, a few hundred years later, and the lands were being plundered and ravaged by barbarians, vandals and scavengers, many former Roman citizens came to realize the life in the city of Letum, or as it was called by the common people, the city of death, was actually appearing to be a lot more safer than life on the mainland had become.
Against all odds, the city of Letum maintained a peaceful society. Even though there were no law enforcers. There were no laws, there was no currency, and there was no obligation to pay taxes. The society successfully relied on the common good, and the good within its people. They were a nation independent of any other. They had enough land for the few farmers to provide the entire city with plenty of food and even food to spare, and those that had not the burden of providing food now had the time to specialize in other crafts, such as architecture, metallurgy, science, philosophy or infrastructure. 
They maintained a form of politics quite alike that which the ancient Greeks had used, one similar to Aristocracy. The land owners and their families, as wealthiest and most considerable members of their society were put and held in charge. The Aristocrats of Letum were called Letumians.
However, alike in the rest of Europe, a new religion under the name of Christianity started to threaten the half Greek half Roman, agricultural roots that made the settlement of Letum into the society it had become. Though most of what had been the Roman Empire had been conquered by Christianity around 600AD, the supposed-to-be barbaric, uncultured treacherous semi-island known as the city of death was mostly left alone or even avoided by preachers and priests who therewith ensured their isolation for a few more decades up until the third crusade in the second half of the twelfth century. 
It was as the crusaders arrived that the city started to live up to its name. Known as the city of death, passing crusaders had no remorse, compassion or sympathy as they passed Letum, rudely ravaging through the peaceful society, getting rid of the peace for good. Letum was plundered, women were raped and children were murdered, but the men remembered their heritage and honored their name of bloodthirsty murderers, decreasing the number of crusaders enough to ensure they would never reach Jerusalem.
However, with the arrival of crusaders in Letum, currency also made its way back into the society of Letum and along with the gold, greed was back on the scene. The Letumians were charged with restoring balance and they created the constitutional laws still in use today, though mostly in disregard by the gangs who run the streets. Along with the constitution, the Letumians called to life a military force with the responsibility of enforcing these new laws, with suiting punishments for those who chose to transgress.
This seemed a working plan. A large building was constructed with marble bars preventing people from getting out through the windows, in which transgressors were locked up for the time being or while awaiting their capital punishment. Meanwhile, Letumians installed taxes to pay for these facilities and for the construction of a harbor to enlarge the minor amount of trading they now did with the main land.
Entering the modern ages, the classic structures that Letum maintained opened the eyes of historians and tourists exploring the ancient cultures and societies, and even though on the northern end of the city Romanic houses had been replaced by factories and harbor facilities, the center and south still had the roman era written all over it. The society adapted to its tourism, however, as a red light district arose near the harbor for the sailors’ desires when they were months away from their loves and many idyllic restaurants and bars opened up all around town, or artists opening up shop to sell their portraits of the city. In this age, their Aristocratic society led by Letumians slowly averted into a democracy of the people choosing a parliament. Although the first decades only Letumians were allowed to vote, in the late 1700s this was broadened to all men. Women’s suffrage would not be instated until forcefully acquired by a group of feminists lead by a woman called Lily Thorn, shortly after the destruction of Letum during the Second World War.   
During the First World War they maintained independence, forming a haven for refugees that had betrayed their homeland, or neutral turf for boats passing from one side to another. Many people decided to visit Letum during this age as its independence ensured a sense of safety, making the city wealthier than it had ever been.
The era of wealth would not last long, however. Though they intended upon keeping their independence and neutral position throughout this war as well, they were subjected to the bombardments that besieged Italy in the last months of 1943 and the remainder of 1944 as Germany invaded its former ally after Italy surrendered to the Allies. Series of bombs plagued Letum in early 1944 destroying most of its ancient culture along with many of its citizens. Their tourists’ attractions all destroyed, it was now the citizens of Letum that started to honor the city’s nickname. As tourists no longer bothered to visit the ruins of Letum the restaurants went bankrupt and many of the city’s population joined one of the various gangs now uprising in the city. The military police forces became corrupt, accepting bribes to look the other way, and criminals had free play.
Nowadays Letum is overrun by various gangs, the sounds of firings guns part of the common day life and the police reluctant to act as the gangs pay them well not to. A city once famous for its peaceful nature and its ability to retain the ancient, classic culture turned into a haven for organized crime, drug barons and warlords.
</body>
